trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
-    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureServiceConnection'
    subscriptionId: 'your-subscription-id'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myResourceGroup'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    overrideParameters: '-storageAccountName $(storageAccountName)'
    deploymentMode: 'Incremental'